# Generated by Django 2.2.6 on 2019-10-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('urls', models.URLField(max_length=100)),
                ('texts', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'books',
            },
        ),
    ]
